require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/clientes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Cliente. As you add validations to Cliente, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cliente.create! valid_attributes
      get clientes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cliente = Cliente.create! valid_attributes
      get cliente_url(cliente)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cliente_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cliente = Cliente.create! valid_attributes
      get edit_cliente_url(cliente)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cliente" do
        expect {
          post clientes_url, params: { cliente: valid_attributes }
        }.to change(Cliente, :count).by(1)
      end

      it "redirects to the created cliente" do
        post clientes_url, params: { cliente: valid_attributes }
        expect(response).to redirect_to(cliente_url(Cliente.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cliente" do
        expect {
          post clientes_url, params: { cliente: invalid_attributes }
        }.to change(Cliente, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post clientes_url, params: { cliente: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cliente" do
        cliente = Cliente.create! valid_attributes
        patch cliente_url(cliente), params: { cliente: new_attributes }
        cliente.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cliente" do
        cliente = Cliente.create! valid_attributes
        patch cliente_url(cliente), params: { cliente: new_attributes }
        cliente.reload
        expect(response).to redirect_to(cliente_url(cliente))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cliente = Cliente.create! valid_attributes
        patch cliente_url(cliente), params: { cliente: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cliente" do
      cliente = Cliente.create! valid_attributes
      expect {
        delete cliente_url(cliente)
      }.to change(Cliente, :count).by(-1)
    end

    it "redirects to the clientes list" do
      cliente = Cliente.create! valid_attributes
      delete cliente_url(cliente)
      expect(response).to redirect_to(clientes_url)
    end
  end
end
