require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/emersons", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Emerson. As you add validations to Emerson, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Emerson.create! valid_attributes
      get emersons_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      emerson = Emerson.create! valid_attributes
      get emerson_url(emerson)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_emerson_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      emerson = Emerson.create! valid_attributes
      get edit_emerson_url(emerson)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Emerson" do
        expect {
          post emersons_url, params: { emerson: valid_attributes }
        }.to change(Emerson, :count).by(1)
      end

      it "redirects to the created emerson" do
        post emersons_url, params: { emerson: valid_attributes }
        expect(response).to redirect_to(emerson_url(Emerson.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Emerson" do
        expect {
          post emersons_url, params: { emerson: invalid_attributes }
        }.to change(Emerson, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post emersons_url, params: { emerson: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested emerson" do
        emerson = Emerson.create! valid_attributes
        patch emerson_url(emerson), params: { emerson: new_attributes }
        emerson.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the emerson" do
        emerson = Emerson.create! valid_attributes
        patch emerson_url(emerson), params: { emerson: new_attributes }
        emerson.reload
        expect(response).to redirect_to(emerson_url(emerson))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        emerson = Emerson.create! valid_attributes
        patch emerson_url(emerson), params: { emerson: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested emerson" do
      emerson = Emerson.create! valid_attributes
      expect {
        delete emerson_url(emerson)
      }.to change(Emerson, :count).by(-1)
    end

    it "redirects to the emersons list" do
      emerson = Emerson.create! valid_attributes
      delete emerson_url(emerson)
      expect(response).to redirect_to(emersons_url)
    end
  end
end
